# See https://yarnpkg.com/configuration/yarnrc for more info on configuring
# yarn v2+.

# The path of a Yarn binary, which will be executed instead of any other
# (including the global one) for any command run within the directory covered by
# the rc file. If the file extension ends with .js it will be required, and will
# be spawned in any other case.
#
# The yarnPath setting is currently the preferred way to install Yarn within a
# project, as it ensures that your whole team will use the exact same Yarn
# version, without having to individually keep it up-to-date.
yarnPath: ".yarn/releases/yarn-berry.cjs"

# Ever since Yarn was created, our very essence has been about experimenting,
# evolving, pushing the status quo - rinse and repeat, each time one step
# further, each time paving the way for our next move.
#
# As you can guess, this philosophy (coupled with the high number of external
# contributions we receive) requires us to iterate fast in order to accommodate
# the various experiments that we brew. In a major step forward, Yarn got
# redesigned in the v2 in order to leverage a new modular API that can be
# extended through plugins. Nowadays, most of our features are implemented
# through those plugins - even yarn add and yarn install are preinstalled
# plugins!
#
# See: https://yarnpkg.com/features/plugins
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

# If true, Yarn will ask for your guidance when some actions would be improved
# by being disambiguated. Enabling this setting also unlocks some features (for
# example the `yarn add` command will suggest to reuse the same dependencies as
# other workspaces if pertinent).
preferInteractive: true

# If true, the CLI will prefix most messages with codes suitable for search
# engines.
enableMessageNames: ${CI:-false}

# If true (the default outside of CI environments), Yarn will periodically send
# anonymous data to our servers tracking some usage information such as the
# number of dependency in your project, how many install you ran, etc.
enableTelemetry: false

# This setting defines the minimal amount of time between two telemetry uploads,
# in days. By default we only send one request per week, making it impossible
# for us to track your usage with a lower granularity.
telemetryInterval: 999999

# By default, we don't assign unique IDs in the telemetry we send, so we have no
# way to know which data originates from which project. This setting can be used
# to force a user ID to be sent to our telemetry server. Frankly, it's only
# useful in some very specific use cases. For example, we use it on the Yarn
# repository in order to exclude our own usage from the public dashboards (since
# we necessarily run Yarn more often here than anywhere else, the resulting data
# would be biased).
telemetryUserId: ""

# Some packages may have been specified incorrectly with regard to their
# dependencies - for example with one dependency being missing, causing Yarn to
# refuse it the access. The packageExtensions fields offer a way to extend the
# existing package definitions with additional information. Note: This field is
# made to add dependencies; if you need to rewrite existing ones, prefer the
# resolutions field.
#
# Each key is a descriptor covering a semver range. The extensions will be
# applied to any package whose version matches the specified range. This is true
# regardless of where the package comes from, so no distinction on whether they
# come from git or a registry, for example. Only the version matters.
packageExtensions:
  "@chakra-ui/provider@1.6.7":
    dependencies:
      "@chakra-ui/react-env": "1.0.6"
      "@chakra-ui/portal": "1.2.9"
