name: Lint JavaScript/TypeScript with ESLint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run ESLint on JavaScript/TypeScript files
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: '--ext .js,.jsx,.ts,.tsx'
